version: '3.3'

services:
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 3000:3000
    depends_on:
      - mydb
      - api
      - daemon

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mydb
    expose:
      - 3232
    ports:
      - 3232:3232
    volumes:
      - ./server:/app
    environment:
      - DATABASE_URL=postgresql://react_to_do:react_to_do@mydb:5432/postgres_dev
      - SECRET_KEY=08d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    command: uvicorn src.api.application:api --reload --host 0.0.0.0 --port 3232

  daemon:
    build:
      dockerfile: Dockerfile
      context: "./daemon"
    depends_on:
      - mydb
      - api
    volumes:
      - ./daemon:/app
    environment:
      - DATABASE_URL=postgresql://react_to_do:react_to_do@mydb:5432/postgres_dev

  mydb:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=react_to_do
      - POSTGRES_PASSWORD=react_to_do
      - POSTGRES_DB=postgres_dev
    volumes:
      - ./services/backend/postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    driver: local
