version: '3.3'

services:
  client:
    stdin_open: true
    container_name: client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - mydb
      - api
      - daemon

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    restart: always
    container_name: api
    depends_on:
      - mydb
    expose:
      - 3232
    ports:
      - 3232:3232
    volumes:
      - ./server:/app
    environment:
      - DATABASE_URL=postgresql://react_to_do:react_to_do@mydb:5432/postgres_dev
    command: bash -c "alembic upgrade head && uvicorn src.api.application:api --reload --host 0.0.0.0 --port 3232"

  daemon:
    build:
      dockerfile: Dockerfile
      context: "./daemon"
    restart: always
    container_name: daemon
    depends_on:
      - mydb
      - api
    volumes:
      - ./daemon:/app
    environment:
      - DATABASE_URL=postgresql://react_to_do:react_to_do@mydb:5432/postgres_dev

  nginx:
    container_name: slava_nginx
    build:
      dockerfile: Dockerfile
      context: "./nginx"
    ports:
      - 3000:3000
    depends_on:
      - api
      - client

  mydb:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=react_to_do
      - POSTGRES_PASSWORD=react_to_do
      - POSTGRES_DB=postgres_dev
    restart: always
    volumes:
      - ./services/backend/postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    driver: local
